version: "3.9"
services:
  app:
    image: myServ
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    profiles:
      - db
  postgres:
    image: postgres
    container_name: postgres
    profiles:
      - db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql