version: "3.9"
services:
  app:
    image: myserv
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: "postgres"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql